version: '3.4'

services:
  exporter:
    image: weather-data-collector
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      TZ: Europe/Zurich
      RUST_LOG: info
    restart: unless-stopped
